server:
  port: 8005

spring:
  redis:
    database: 0
    host: 172.20.10.9
    port: 6379
    password: '010816'
    timeout: 5000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


website:
  domain-name: imoocnews.com